DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS organisations;
DROP TABLE IF EXISTS "Events";
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS bases;
